export default {
    getSite: '/site',
    getCategory: '/category',
    register: '/admin/register',
    login: '/admin/login',
    getAdminInfo: '/admin/info',
    logout: '/admin/logout',
    setWebsite: '/admin/set-website',
    getFrontUsers: '/admin/front-user',
    forbidFrontUser: '/admin/forbid-front-user',
    unfreezeFrontUser: '/admin/unfreeze-front-user',
    deleteFrontUser: '/admin/delete-front-user',
    getAdminUsers: '/admin/admin-user',
    addAdmin: '/admin/add-admin',
    forbidAdminUser: '/admin/forbid-admin-user',
    unfreezeAdminUser: '/admin/unfreeze-admin-user',
    deleteAdminUser: '/admin/delete-admin-user',
    getPostList: '/admin/post-list',
    getPostDetail: '/admin/post-detail',
    reviewPost: '/admin/review-post',
    getPostState: '/admin/post-state',
    getAttachment: '/admin/get-attachment',
    updateCategory: '/admin/update-category',
    addGift: '/admin/add-gift',
    getGiftCate: '/giftcate',
    getGiftsList: '/admin/get-gifts'
}