export default {
  site: '/setting',
  category: '/category',
  member: '/member',
  loginMember: '/member/login',
  logoutMember: '/member/logout',
  memberInfo: '/member/info',
  address: '/address',
  postInsert: '/post/insert',
  post: '/post',
  postlist: '/post/list',
  postState: '/post_state',
  postAttachment: '/post/attachment',
  giftCategory: '/gift_category',
  giftList: '/gift/list',
  gift: '/gift',
  exchangeGift: '/gift/order',
  giftOrderList: '/gift_order/list',
  giftOrder: '/gift_order',
  noticeList: '/notice/list',
  notice: '/notice',
  noticeAttachment: '/notice/attachment',
  memberRanking: '/member/ranking',
  pointsRecord: '/points_record',
  scoreRecord: '/score_record',
  tracking: 'http://api.kdniao.com/Ebusiness/EbusinessOrderHandle.aspx'
}
