export default {
    getSite: '/site',
    getCategory: '/category',
    getCategoryMap: 'category-map',
    register: '/user/register',
    login: '/user/login',
    getUserInfo: '/user/info',
    logout: '/user/logout',
    getMember: '/user/get-member',
    updateMember: '/user/update-member',
    setAvatar: '/user/set-avatar',
    addAddress: '/user/add-address',
    editAddress: '/user/edit-address',
    deleteAddress: '/user/delete-address',
    getAddressList: '/user/address-list',
    insertImg: '/user/insert-image',
    submitPost: '/user/submit-post',
    getPostList: '/user/post-list',
    getPostDetail: '/user/post-detail',
    getPostState: '/user/post-state',
    getAttachment: '/user/get-attachment'
}